# Generated by Django 4.1.1 on 2022-09-26 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('randomApplication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='blockList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromBlock', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toBlock', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
