# Generated by Django 4.1.1 on 2022-09-26 15:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randomApplication', '0002_blocklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blockList',
            field=models.ManyToManyField(blank=True, related_name='blockUsers', to=settings.AUTH_USER_MODEL),
        ),
    ]
