# Generated by Django 4.1.1 on 2022-09-28 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CRUD', '0003_post_likepost_commentpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentpost',
            name='userComment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserComment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='likepost',
            name='userLike',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserLike', to=settings.AUTH_USER_MODEL),
        ),
    ]
