# Generated by Django 4.1.1 on 2022-10-04 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginRegisterAPI', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
